### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by jsaltzman** [romedtino/simple-wyze-vac#11]
I am trying to install this within a docker container running Home Assistant. First I got an error re: git but I got it installed in the docker container. Now I get the following error:

Unable to import component: No module named 'wyze_sdk'

Is there a way I can fix this?

**Comment by romedtino** [comment]
Usually when installed through HACS, it should automatically pip install the appropriate dependencies. One of them being `wyze_sdk`. There might have been something that went wrong after installing. Did you make sure to restart Home Assistant after installing through HACS? 

You can also try removing `simple-wyze-vac`, restart Home Assistant, reinstall through HACS, restart and see if it starts working.
