### ISSUE TITLE
Can Filter and Brush Life be retrieved with SDK?

### ISSUE THREAD

**Issue by iceman73** [romedtino/simple-wyze-vac#12]
Like the title says, would love to track life of filter and brushes to send a reminder when they are at the end of their life.

**Comment by romedtino** [comment]
I'm a bit in the mercy of the underlying API - https://github.com/shauntarves/wyze-sdk . So it might be better to request these features there

**Comment by iceman73** [comment]
Done:
https://github.com/shauntarves/wyze-sdk/issues/64

**Comment by romedtino** [comment]
I have a pre-release version that has this implemented if you're interested to try it out early - https://github.com/romedtino/simple-wyze-vac/releases/tag/v1.5.1

Just hit the `show beta buttons` from within HACS and you should see an option to install v1.5.1. Seems to work well enough (just ignore the numbers you see for mine haha)

![image](https://user-images.githubusercontent.com/18567128/160922320-91a358cd-f7cf-4add-948b-65ecd17bbed3.png)

**Comment by romedtino** [comment]
Closed #16

**Comment by iceman73** [comment]
Thankyou for this
