### ISSUE TITLE
Protobuff error on startup

### ISSUE THREAD

**Issue by sergeknystautas** [romedtino/simple-wyze-vac#25]
I used to be able to access my vacuum state using the wyze add-on and the simple-wyze hacs, but I assume from the recent updates that I'm now seeing a protobuff parse error in the logs and my vacuum entity is not available.  I'm on simple-wyze 1.6.1 and wyze 0.1.8.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/simple_wyze_vac/vacuum.py", line 76, in setup_platform
    vacs.append(WyzeVac(hass.data[WYZE_VAC_CLIENT], pl, username, password, polling))
  File "/config/custom_components/simple_wyze_vac/vacuum.py", line 108, in __init__
    self.update()
  File "/config/custom_components/simple_wyze_vac/vacuum.py", line 303, in update
    self._rooms = self.get_rooms(vacuum)
  File "/config/custom_components/simple_wyze_vac/vacuum.py", line 347, in get_rooms
    for room in vacuum.current_map.rooms:
  File "/usr/local/lib/python3.9/site-packages/wyze_sdk/models/devices/vacuums.py", line 368, in rooms
    map_data = self.parse_blob(blob=self._blob)
  File "/usr/local/lib/python3.9/site-packages/wyze_sdk/models/devices/vacuums.py", line 406, in parse_blob
    map, typedef = blackboxprotobuf.protobuf_to_json(base64.b64decode(base64.b64encode(decompressed)), 'robot_map')
  File "/usr/local/lib/python3.9/site-packages/blackboxprotobuf/lib/interface.py", line 75, in protobuf_to_json
    value, message_type = decode_message(buf, message_type)
  File "/usr/local/lib/python3.9/site-packages/blackboxprotobuf/lib/interface.py", line 62, in decode_message
    value, typedef, _ = blackboxprotobuf.lib.types.length_delim.decode_message(buf, message_type)
  File "/usr/local/lib/python3.9/site-packages/blackboxprotobuf/lib/types/length_delim.py", line 271, in decode_message
    if isinstance(output[field_number], list):
KeyError: '5'
```

**Comment by romedtino** [comment]
Hi, do you mind checking what your vacuum  firmware version is? This might be a duplicate already here - https://github.com/romedtino/simple-wyze-vac/issues/9

**Comment by sergeknystautas** [comment]
Yes, my firmware is 1.6.173 as I wanted the multi-room support, but this was working a week ago so I don't think it's in the same place of the code.  Also, this is when simply getting status and reading the map data, not when sending a sweep command.  I would guess the status was working previous with 1.6.173 but when reading the map image was added, it would break, but that's just by reading what was part of the release and a scan of the methods in the stack trace, not reading the code.

**Comment by sergeknystautas** [comment]
Ok, so we're both right.  romedtino in the commit [6fb756](https://github.com/romedtino/simple-wyze-vac/commit/6fb756d313e29fb2ae2f3833586be6d2511974eb) to add room as attributes makes a call to  `vacuum.current_map.rooms`.  This is the call that prior to this commit was happening in sweep_room.

So it is the same root cause, that vacuum.current_map.rooms does not support firmware 1.6.173.  The problem is that instead of only breaking one action, it now breaks the entire integration.

**Comment by romedtino** [comment]
Gotcha, yeah that makes sense. I think I can actually workaround that json issue since I ended up forking wyze-sdk. For now, if you don't mind just use an older release. And I'll get that fix out. Thanks!

**Comment by romedtino** [comment]
@sergeknystautas Do you mind trying pre-release 1.6.2? Update information in HACS, make sure show beta versions is checked and try 1.6.2? Since it's just a workaround, you probably won't see the `rooms` attribute fill in correctly since it can't actually parse the blob correctly but hopefully it still allows you to do other things not related to rooms. Thanks!

**Comment by sergeknystautas** [comment]
I picked up the 1.6.2 pre-release version, but I'm seeing the same stack trace (looked it over and the same line numbers).  I'm guessing it's not picking up your forked wyze-sdk... is there a way I can check that?  I poked around the file system but wasn't sure where HA is storing the cached python dependencies.

**Comment by romedtino** [comment]
Ah, yeah I flubbed updating the version number in version.py. There should now be a 1.6.3 beta release and hopefully that should be smart enough to get the newer wyze_sdk version. I just tried it on my box and it seems to have worked. Mind trying that?

**Comment by sergeknystautas** [comment]
Thanks, I super appreciate the iteration and happy to reload and debug this.   1.6.3 got me the new forked version of the wyze_sdk so progress, and now I get a different stack trace.

`File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)`
`File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)`
`File "/config/custom_components/simple_wyze_vac/vacuum.py", line 76, in setup_platform
vacs.append(WyzeVac(hass.data[WYZE_VAC_CLIENT], pl, username, password, polling))`
`File "/config/custom_components/simple_wyze_vac/vacuum.py", line 108, in __init__
self.update()`
`File "/config/custom_components/simple_wyze_vac/vacuum.py", line 303, in update
self._rooms = self.get_rooms(vacuum)`
`File "/config/custom_components/simple_wyze_vac/vacuum.py", line 347, in get_rooms
for room in vacuum.current_map.rooms:`
`File "/usr/local/lib/python3.9/site-packages/wyze_sdk/models/devices/vacuums.py", line 369, in rooms
if 'roomDataInfo_' in map_data:`
`TypeError: argument of type 'NoneType' is not iterable`

**Comment by romedtino** [comment]
Alright, *I think* I quelled those `None` issues. Try beta 1.6.4?

**Comment by romedtino** [comment]
ah dangit yea I missed the `vacuum.current_map.rooms` call there good catch at least that's only in the custom_component and not in wyze_sdk anymore. I'll do a fix for it. Thanks for all the help!

**Comment by sergeknystautas** [comment]
Sure thing... now I get a clean message on sweep_room call.  Everything is functional now.
_No rooms from Wyze servers. You may have the unsupported multi-floor firmware. Sweep rooms currently does not work on this firmware._

Thank you for all of the work on this!

**Comment by romedtino** [comment]
Nice glad it works! When Wyze fully rolls out that firmware I'll take a stab and see if we can get sweep room support on that firmware.

**Comment by romedtino** [comment]
Gotcha, yeah that makes sense. I think I can actually workaround that json
issue since I ended up forking wyze-sdk. For now, if you don't mind just
use an older release. And I'll get that fix out. Thanks!
