### ISSUE TITLE
Filter Hours

### ISSUE THREAD

**Issue by razor05** [romedtino/simple-wyze-vac#26]
The remaining filter hours is incorrect for my vacuum.   It appears to be the result of subtracting the number of hours used from recommended/ theoretical hours from Wyze, but it seems to be using 100 for the filter rather than 150.  Is this mathematical function being done via the HA attribute?

**Comment by romedtino** [comment]
You're right, It's just some constant in the const.py file. I've gone ahead pushed a new release with that changed.

**Comment by romedtino** [comment]
closed in https://github.com/romedtino/simple-wyze-vac/releases/tag/1.6.6

**Comment by razor05** [comment]
Thanks for the quick update!
