### ISSUE TITLE
Failed to login Wyze servers.

### ISSUE THREAD

**Issue by brianhanifin** [romedtino/simple-wyze-vac#30]
```
This error originated from a custom integration.

Logger: custom_components.simple_wyze_vac.config_flow
Source: custom_components/simple_wyze_vac/config_flow.py:51 
Integration: Simple Wyze Vac (documentation) 
First occurred: 1:53:34 PM (1 occurrences) 
Last logged: 1:53:34 PM

Failed to login Wyze servers.
```
I tried logging in with my primary account, then I setup a secondary account that I shared my vacuums with. When the secondary login didn’t work, I tried adding 2FA to the secondary account. None of those changed it.

I also have the Wyze integration, which works correctly. So I don’t know why this integration wouldn’t be able to connect to the Wyze server.

Home Assistant 2022.5.5
Simple Wyze Vac 1.7

**Comment by romedtino** [comment]
Hmm, that error simply states it cannot login to the Wyze servers. The other wyze integration uses a completely different mechanism to do Wyze requests so we can't fully compare them. I just tried readding my Wyze account and it seems to work okay (with or without 2FA). For the non-2FA version, are you leaving the `totp` section blank and for the 2FA section did you follow the guide here - https://github.com/romedtino/simple-wyze-vac#totp ?

**Comment by brianhanifin** [comment]
OK. I tried again today and the error is different now.

```
Error setting up entry Simple Wyze Vac for simple_wyze_vac

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/simple_wyze_vac/__init__.py", line 69, in async_setup_entry
    if vac_info.current_map.rooms is not None:
  File "/usr/local/lib/python3.9/site-packages/wyze_sdk/models/devices/vacuums.py", line 380, in rooms
    return [VacuumMapRoom(**room) for room in map_data['12']]
  File "/usr/local/lib/python3.9/site-packages/wyze_sdk/models/devices/vacuums.py", line 380, in <listcomp>
    return [VacuumMapRoom(**room) for room in map_data['12']]
TypeError: wyze_sdk.models.devices.vacuums.VacuumMapRoom() argument after ** must be a mapping, not str
```
