### ISSUE TITLE
Error setting up new integration.

### ISSUE THREAD

**Issue by justinmyersm** [romedtino/simple-wyze-vac#32]
I was using the previous version fine, then when I upgraded to the new version, I get the following error:

> This error originated from a custom integration.
> 
> Logger: homeassistant.config_entries
> Source: custom_components/simple_wyze_vac/__init__.py:81
> Integration: Simple Wyze Vac (documentation)
> First occurred: 11:27:16 PM (1 occurrences)
> Last logged: 11:27:16 PM
> 
> Error setting up entry Simple Wyze Vac for simple_wyze_vac
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/simple_wyze_vac/__init__.py", line 81, in async_setup_entry
>     "room_manager": room_manager
> UnboundLocalError: local variable 'room_manager' referenced before assignment

This has been the same error I have received each time I have attempted to set it up. I uninstalled the custom integration, removed any reference in configuration.yaml, and removed the custom respiratory in HACS. I restarted HA and didn't add it back for a couple of days. I did a Core update to HA along with an OS update and figured I would give it another shot; same error. 

> Home Assistant Core 2022.6.1
> Home Assistant Supervisor 2022.05.3
> Home Assistant OS 8.1
> Wyze Vacuum Firmware 1.6.173
> Wyze Vacuum Plugin 2.31.9

**Comment by romedtino** [comment]
Hm this is definitely a bug on my part fix incoming.

**Comment by justinmyersm** [comment]
Thank you! If there is any more information you need from me, I will be happy to provide more details.

**Comment by romedtino** [comment]
Perhaps the Wyze servers were down during this time? Looking at that error log, there's not much on my end that I can see changing as the errors seem to just be accessing the Wyze servers themselves.

I just tried removing/ adding my own credentials (no 2FA) and I logged in just fine.

Can you share your vacuum firmware version?

**Comment by romedtino** [comment]
I see, that firmware version is higher than the current release of `1.6.113` maybe Wyze did something again and changed how the API works for newer firmware.  I can take a look a bit more but this might just be another Wyze API change and could be something that needs to be modified on the `wyze-sdk` side. `1.6.202` is even newer than the `1.6.173` that was floating around...

**Comment by mboarman** [comment]
Ugh! I was hoping for a simple fix. My wife is not happy! lol....Please keep us posted if you find anything. Thanks!!

**Comment by mboarman** [comment]
Update: Went and tried installing the integration again tonight and IT WORKED! It had to be something on the Wyze end. Hopefully it stays in place! Sorry for the fire drill!

**Comment by romedtino** [comment]
Great! Glad it's working!
