### ISSUE TITLE
sweep_auto not an available service?

### ISSUE THREAD

**Issue by seanemclean** [romedtino/simple-wyze-vac#35]
First, this integration is awesome - thank you! I just recently updated it and redid my setup via the UI, all devices and entities added as expected. I'm trying to setup an evening clean using the sweep_auto command in Node Red, but the only service call available for simple wyze vacuum is 'sweep rooms' - this ignores any constraints from the room switches.

Is there a step or yaml configuration I'm missing to enable sweep auto?

**Comment by romedtino** [comment]
There should be a service already for that built right into home assistant `service: vacuum.return_to_base`

**Comment by romedtino** [comment]
Seems to be complete.
