### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Braden-Hale22** [romedtino/simple-wyze-vac#45]
**Describe the bug**
After Following the steps for setup all of my devices have been deleted from my wyze account and now the simple wyze vac integration wont accept my login credentials no matter what. 

Simple Wyze Vac Version = 1.7.2

Home Assistant Version = 2022.10.0

**Comment by romedtino** [comment]
Hey, I think you're going to have to go into more detail as to what you had done. Have you taken any steps to debug the issue?

It's not possible for this integration to wipe any device from your wyze account. It doesn't run anything remotely close to that. It just queries the available devices, narrows down to available Wyze vacuums and that's it.
