### ISSUE TITLE
No Vacuum Entity Showing Up with Firmware 1.6.306

### ISSUE THREAD

**Issue by treefire** [romedtino/simple-wyze-vac#48]
I am working on getting my Wyze Vac set up in HA and it is only showing up with the camera entity and the rooms that I have mapped. Do you believe that this is due to the newer version of firmware or am I doing something incorrectly? I have followed the instructions as outlined. I appreciate any help you can provide!

**Comment by treefire** [comment]
Well, nevermind. I don't know why, but it is showing up now. Sorry for the trouble.

**Comment by tomgie** [comment]
I am having the same issue. Do you know what you did to fix the problem?

**Comment by treefire** [comment]
I did a full scan and vacuum cycle through the wyze app. It appeared after that. Not sure if that did it or it was just time.

**Comment by tomgie** [comment]
Must have been a fluke. Can't seem to get it to work no matter what.

**Comment by romedtino** [comment]
Wyze had some outtages the past couple days. It could be related? Try either 

Settings -> Devices & Services -> Simple Wyze Vac -> Reload

If this doesn't work, try to delete and reinstall? 

Settings -> Devices & Services -> Simple Wyze Vac -> Delete -> Restart Home Assistant -> Reinstall

I have not tested this new firmware though if it has worked for other folks, I would think the newer version is not the culprit.

**Comment by tomgie** [comment]
Both methods do not work. The room controls and camera show up, but not the robot itself. I am on firmware version 1.6.306

**Comment by romedtino** [comment]
Odd, anything in the logs? Maybe something in that version has changed the way vacuums are identified

**Comment by tomgie** [comment]
Here's the home assistant logs.
https://gist.github.com/tomgie/4b91c84bdb82b1e08503e343c5e5c05f

**Comment by treefire** [comment]
I have that same firmware version and mine is working correctly.

**Comment by romedtino** [comment]
> Here's the home assistant logs. https://gist.github.com/tomgie/4b91c84bdb82b1e08503e343c5e5c05f

Interesting, it's not able to write to `<home_assistant_install_dir>/www/simple_wyze_vac`.
What device are you running Home Assistant on, an RPi?

You can try creating the directory manually. Usually that www/ directory is where you can put files that are accessible via 
`http://homeassistant.local/local/` e.g. `http://homeassistant.local/local/somefiles.png`

**Comment by tomgie** [comment]
My Home Assistant setup runs in a docker container. I've create the directory before and even tried a+rwx for both directories without anything working.

**Comment by romedtino** [comment]
Hm, I'm behind a docker container as well. When you put a png file in that directory, are you able to access it via `http://homeassistsant.local/local/somefiles.png` ?

**Comment by tomgie** [comment]
Yep works completely fine.

**Comment by droptopgokart** [comment]
Just bought a wyzevac today. Same issue. Shows rooms and camera entity but the vacuum entity is missing.

**Comment by romedtino** [comment]
Hm, without a vacuum with this specific firmware, it's a bit hard to debug. The camera and rooms showing up are entities made directly. The only one that is generated from the `wyze-sdk` is the vacuum which is the one missing. This points me to think it's the connection to the wyze account/API.

@droptopgokart are the contents of your logs the same as the one listed above?

Are you guys using 2FA to access your accounts?

**Comment by droptopgokart** [comment]
> Hm, without a vacuum with this specific firmware, it's a bit hard to debug. The camera and rooms showing up are entities made directly. The only one that is generated from the `wyze-sdk` is the vacuum which is the one missing. This points me to think it's the connection to the wyze account/API.
> 
> @droptopgokart are the contents of your logs the same as the one listed above?
> 
> Are you guys using 2FA to access your accounts?

Not using 2FA also vacuum entity is there now after a few hours.  Then doing a reload.  But now neither  the polling or manual service call to update the battery level and such so digging into that.

**Comment by tomgie** [comment]
> Not using 2FA also vacuum entity is there now after a few hours. Then doing a reload. But now neither the polling or manual service call to update the battery level and such so digging into that.

Did you do a full clean?

**Comment by droptopgokart** [comment]
> > Not using 2FA also vacuum entity is there now after a few hours. Then doing a reload. But now neither the polling or manual service call to update the battery level and such so digging into that.
> 
> Did you do a full clean?

Like let the vacuum clean the entire map?  If so yes.

**Comment by droptopgokart** [comment]
Still haven't been able to get the status to update and now the vac is unavailable.![Screenshot_20230109_065701_Home Assistant.jpg](https://user-images.githubusercontent.com/77134315/211313411-4174c890-f4c0-4988-9cae-c887e37ee7b8.jpg)

**Comment by evanhfox** [comment]
Just factory set one of my Wyze vacuums and added it to new account and have added this account to the Simple Wyze Vac HASS integration. I'm having the same issue... Wyze vacuum camera sensor and all the rooms detected as switches, but no entity for the vacuum itself. No 2FA and I've removed and re-installed the addon, still not seeing a vacuum entity.

**Comment by evanhfox** [comment]
Just to add an update, after a few rooms being cleaned, the vacuum entity has appeared after a reload of the integration.

Looking at the logs it appears that the entity isn't added due to the last vacuumed picture being unavailable from Wyze. Once an initial vacuum completes, this error goes away and the vacuum entity is added to HASS.

**Comment by kariudo** [comment]
> due to the last vacuumed picture being unavailable from Wyz

This seems like the sort of thing that should try/catch into a default placeholder image if one cannot be retrieved yet, rather than break the loading/availability of the vacuum entity.

**Comment by romedtino** [comment]
If you're still having this issue please try beta 1.7.3 https://github.com/romedtino/simple-wyze-vac/releases/tag/1.7.3

**Comment by tomgie** [comment]
This has seemed to fix the issue! Thank you.

**Comment by mxc42** [comment]
I'm still running into either the same or similar issue on 1.7.3:

```
simple_wyze_vac: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    await task
  File "/config/custom_components/simple_wyze_vac/vacuum.py", line 361, in async_update
    await self.get_last_map()
  File "/config/custom_components/simple_wyze_vac/vacuum.py", line 392, in get_last_map
    url = await self.hass.async_add_executor_job(lambda: self._client.vacuums.get_sweep_records(device_mac=self._vac_mac, since=datetime.now())[0].map_img_big_url)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/simple_wyze_vac/vacuum.py", line 392, in <lambda>
    url = await self.hass.async_add_executor_job(lambda: self._client.vacuums.get_sweep_records(device_mac=self._vac_mac, since=datetime.now())[0].map_img_big_url)
IndexError: list index out of range
```

This is with a new vacuum, first time using this integration. Entities for each room show up, along with a camera entity.
