### ISSUE TITLE
Configuration validation won't let me restart

### ISSUE THREAD

**Issue by codypet** [romedtino/simple-wyze-vac#5]
Configuration validation just spools and I can't restart after installing application and setting up the config file.

I'm running core-2021.9.6

When I tried a hard restart of HA my google devices disconnected.  They reappeared after I deleted the integration.   The vacuum entities never showed up.

This is the error I get in my for my nest and when I restart.
https://hastebin.com/efasulezeq

**Comment by romedtino** [comment]
The process should be install it through HACS then in your Home Assistant configuration.yaml you add an entry like

```
simple_wyze_vac:
  username: myEmail4Wyze@email.com
  password: myWyzePassword
```

Make sure to hit that check configuration button
![image](https://user-images.githubusercontent.com/18567128/134232809-620c0484-5569-4a87-9dc6-c8bb83302ead.png)

and a vacuum entity should show up on reboot.

I don't believe this integration interferes or connects to anything google nest related so I'm not sure what to make of your log

**Comment by romedtino** [comment]
Oh I see. Interesting bug. Did you try installing the Wyze-HA update with a newere protobuf version declared to see if that fixes it?

**Comment by codypet** [comment]
So I'm running this on VirtualBox and for some reason when I run it, it doesn't change anything.   I'm not sure if I'm installing protocol wrong or what?

**Comment by romedtino** [comment]
Hmm, is it virtual box with a docker container of HA? If I check my copy of home assistant on docker, it shows protobuf at 3.10.0
![image](https://user-images.githubusercontent.com/18567128/134250760-e2ad4829-35f5-4771-9e9b-d0c25dda55f7.png)

Before wyze-sdk updated to fix the login issue, I had recommended people to manually remote into their HA instance and change a line of code in the wyze-sdk instance. Perhaps you can do something similar to update protobuf?

Remote into your HA docker VM/instance and do a `pip install protobuf==3.13.0` ?

**Comment by codypet** [comment]
Yea for some reason my VM doesn't recognize those commands.  Its like its speaking a whole different language in VM.  I don't know why I can't get that info.

**Comment by romedtino** [comment]
I've added the dependency to protobuf as stated in the issue mentioned above. Please let me know if you're still having issues, if not I'll probably close this issue in a few days :)
