### ISSUE TITLE
Individual rooms not cleaning

### ISSUE THREAD

**Issue by dwdonnelly** [romedtino/simple-wyze-vac#50]
Set up an automation to run at a specific time to clean one room on the main floor.

Time triggered automation.  Automation ran.  Vac did not move.

Following error report:

`This error originated from a custom integration.

Logger: custom_components.simple_wyze_vac
Source: custom_components/simple_wyze_vac/__init__.py:76
Integration: Simple Wyze Vac (documentation)
First occurred: 9:35:29 PM (1 occurrences)
Last logged: 9:35:29 PM

Failed to query vacuum rooms. If your firmware is higher than 1.6.113, rooms is currently not supported. Exception: wyze_sdk.models.devices.vacuums.VacuumMapRoom() argument after ** must be a mapping, not str`

I confirmed my vacuum firmware is above 1.6.113. It is at 1.6.202.

Correct Simple Wyze Vac to support rooms.

**Simple Wyze Vac Version**
-1.7.3

**Wyze Vacuum Firmware Version**
-1.6.202

**Home Assistant Version**
-2023.2.2

**Additional context**
Vac does run when "Let iRobot Clean" is selected, but not when a room is selected.

**Comment by romedtino** [comment]
> I confirmed my vacuum firmware is above 1.6.113. It is at 1.6.202.
I think you misread the warning - If your firmware is higher than 1.6.113, rooms is currently **not** supported. 

> Vac does run when "Let iRobot Clean" is selected, but not when a room is selected.
I have no idea what this means? There shouldn't be any iRobot anywhere as this is a Wyze Vac?

**Comment by dwdonnelly** [comment]
Understand the version level.  Since my system is 1.6.202, I can still select a room or rooms to be cleaned via a "service" in the automation - I thought this should not be possible?  See automation via a service:

`alias: iRobot Cleans
description: ""
trigger:
  - platform: time
    at: "11:09:00"
condition: []
action:
  - service: simple_wyze_vac.sweep_rooms
    data:
      entity_id: vacuum.irobot
      rooms:
        - switch.swv_room_10
mode: single`

so the error is not associated? 

iRobot is how I named the vac.  And automated (not via a service):
`description: Lights off and iRobot2 cleans livingroom
trigger:
  - platform: numeric_state
    entity_id: zone.home
    below: 1
condition: []
action:
  - type: turn_off
    device_id: 757ebd28a127f82617cb8ed1e618fdb2
    entity_id: switch.kitchen_light_sw
    domain: switch
  - device_id: c8b551e4e414bc680752e91ad5c86a2d
    domain: vacuum
    entity_id: vacuum.irobot2
    type: clean
  - type: turn_off
    device_id: 989afae12f3360e3cfb7c2b58e520463
    entity_id: light.dinning_room_light_sw
    domain: light
mode: single`

**Comment by dwdonnelly** [comment]
Will close this issue, as I need to further investigate offline, as the routine is working.  Thanks.

**Comment by dwdonnelly** [comment]
Will close this issue, as I need to further investigate offline, as the routine is working. Thanks.
