### ISSUE TITLE
State is Error when Cleaning

### ISSUE THREAD

**Issue by delzear** [romedtino/simple-wyze-vac#52]
**Describe the bug**
Every time I start the vacuum, either with the app or in home assistant, the state goes to "Error". No errors generated in the logs.

**Expected behavior**
State should be "Cleaning"

**Screenshots**
![image](https://user-images.githubusercontent.com/727891/226995911-627c3b06-ae81-4c66-ba75-923aecb77f9f.png)

**Simple Wyze Vac Version**
1.8

**Wyze Vacuum Firmware Version**
1.6.202

**Home Assistant Version**
2023.3.5

**Comment by romedtino** [comment]
Definitely a bug. Should be fixed in 1.8.1 - https://github.com/romedtino/simple-wyze-vac/releases/tag/1.8.1

For more detail, new enumeration for `SWEEPING` in `wyze_sdk` now exists called `CLEANING` and I didn't include it in the check for which activity the vacuum is performing.
