### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by dnestico** [romedtino/simple-wyze-vac#53]
My vacuum says it is up to date and it is on "1.6.173", is it safe to update the addon or do you not know if it will work with that?

**Comment by romedtino** [comment]
I unfortunately do not know if it works for that firmware version. Though it doesn't hurt to update to Simple Wyze Vac `1.8.1` and see if it does. If it doesn't, you should be able to roll back by going to HACS -> Simple Wyze Vacuum -> Top Right 3 Dot Menu -> Redownload -> Select an older version e.g. `1.7.3`

**Comment by dnestico** [comment]
Alright thanks, will try it out later this week.
