### ISSUE TITLE
[BUG] After removing and re-adding integration, TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by SpartanTech** [romedtino/simple-wyze-vac#55]
**Describe the bug**
I moved my vacuum from my work to family account and after deleting and re-adding the integration, it fails to add now. I get a TypeError, unsupported errand type. It was working fine today before I removed the integration to add the new account. Tried with F2A email, F2A auth token, and F2A disabled. I don't believe the firmware was auto-updated, it didn't tell me if so

**To Reproduce**
1. Remove integration
2. Re-Add integration
3. Will enable the integration successfully but fails failed to load, check error logs
4. Logs say Error setting up entry
5. `vacuums.py, TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'`

**Expected behavior**
Successful add just like right before.

**Screenshots**
![Screenshot 2023-04-04 182522](https://user-images.githubusercontent.com/3395163/229944403-266c550e-a474-4db6-ba56-f0868110b61a.png)

**Simple Wyze Vac Version**
1.82

**Wyze Vacuum Firmware Version**
1.6.306

**Home Assistant Version**
2023.3.6

**Additional context**

**Comment by romedtino** [comment]
`1.6.202` is the max I can personally support in regards to Wyze Firmware Version. I would need someone else who has 1.6.306 to do the testing to fix this sort of issue. And I don't know if the error you see is the only one as well. 

It seems on 1.6.306, the variable `self.usage` is no longer populated. This might be better off as an issue to file against https://github.com/shauntarves/wyze-sdk to either capture cases where `self._usage` is None and convert it to an `int` prior to subtracting or guarantee it to be an int? 

If you're savvy enough, you can remote into your Home Assistant instance, go to `/usr/local/lib/python3.10/site-packages/wyze_sdk/models/devices/vacuums.py` and change line 970 from

```
self.type.max_hours - self.usage
```
to 
```
self.type.max_hours - int(self.usage or 0)
```

Then reboot HA and see if Simple Wyze Vac gets further in the initialization process. But keep in mind, your vacuum will just always return max hours since it could not actually query actual usage.

**Comment by SpartanTech** [comment]
> `1.6.202` is the max I can personally support in regards to Wyze Firmware Version. I would need someone else who has `1.6.306` to do the testing to fix this sort of issue. And I don't know if the error you see is the only one as well.
> 
> It seems on `1.6.306`, the variable `self.usage` is no longer populated. This might be better off as an issue to file against https://github.com/shauntarves/wyze-sdk to either capture cases where `self._usage` is None and convert it to an `int` prior to subtracting or guarantee it to be an int? Or dig out the correct _new_ way to get usage value out
> 
> If you're savvy enough, you can remote into your Home Assistant instance, go to `/usr/local/lib/python3.10/site-packages/wyze_sdk/models/devices/vacuums.py` and change line 970 from
> 
> ```
> self.type.max_hours - self.usage
> ```
> 
> to
> 
> ```
> self.type.max_hours - int(self.usage or 0)
> ```
> 
> Then reboot HA and see if Simple Wyze Vac gets further in the initialization process. But keep in mind, your vacuum will just always return max hours since it could not actually query actual usage.

That's what I thought, it didn't notify me it updated, I guess it must have updated since the last time I added the integration.

Thanks a bunch for the quick reply. Musician for the last 10 years, but I graduated computer science, so as long as I'm pointed in the right direction I can usually handle it myself 🤣, thanks for the nudge. I'll take a look at that file when I get home. 

If you need any data from something specific, I can provide that as well no problem.

**Comment by SpartanTech** [comment]
![Screenshot_20230406_005317_Termius](https://user-images.githubusercontent.com/3395163/230283855-9086f0a0-8695-46ea-886e-c06b44f5eeec.jpg)
Do you know which of these locations I should edit? Seems I have a different python version as well as different install version. This box is running raspberry OS supervised install. 

Or should I edit it through terminal in one of the docker containers

**Comment by SpartanTech** [comment]
> > `1.6.202` is the max I can personally support in regards to Wyze Firmware Version. I would need someone else who has `1.6.306` to do the testing to fix this sort of issue. And I don't know if the error you see is the only one as well.
> > It seems on `1.6.306`, the variable `self.usage` is no longer populated. This might be better off as an issue to file against https://github.com/shauntarves/wyze-sdk to either capture cases where `self._usage` is None and convert it to an `int` prior to subtracting or guarantee it to be an int? Or dig out the correct _new_ way to get usage value out
> > If you're savvy enough, you can remote into your Home Assistant instance, go to `/usr/local/lib/python3.10/site-packages/wyze_sdk/models/devices/vacuums.py` and change line 970 from
> > ```
> > self.type.max_hours - self.usage
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> > self.type.max_hours - int(self.usage or 0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then reboot HA and see if Simple Wyze Vac gets further in the initialization process. But keep in mind, your vacuum will just always return max hours since it could not actually query actual usage.
> 
> That's what I thought, it didn't notify me it updated, I guess it must have updated since the last time I added the integration.
> 
> Thanks a bunch for the quick reply. Musician for the last 10 years, but I graduated computer science, so as long as I'm pointed in the right direction I can usually handle it myself 🤣, thanks for the nudge. I'll take a look at that file when I get home.
> 
> If you need any data from something specific, I can provide that as well no problem.

I had to edit home assistant directly via docker, but I found the file and modified it. It works just perfect now, that was the exact issue!

Do you know what would reset the file change? Would a wise vacuum update, a home assistant update, or system reboot reset that file?

**Comment by SpartanTech** [comment]
No one happens to have any experience with docker modifications do they? After I edited the file, home assistant updated and removed the edit. I'm guessing I need to edit a different file or clonr my own sdk? What's the easiest way for that line change to be persistent

**Comment by romedtino** [comment]
Unfortunately whenever HA updates, it will essentially pull fresh copies of the addons and all that. So everytime HA updates, you would have to change it. It should at least persist on reboots. 

So did that change work for you? With that workaround, have you tried to see if the rest of the functionality is there (start vac/pause vac/go dock/etc.)? If so, I wouldn't mind updating the version of `wyze-sdk` I use to add that int check. Let me know 👍

**Comment by SpartanTech** [comment]
Ah I see. Yeah, editing the file allows the integration to load and show the map, but other things fail. Starting, Stopping, and Docking commands work, but show Error on Home Assistant (as if it didnt work). Polling also gives errors when enabled. So in short, sends the commands ok seems like but room selection cleaning and receiving data back shows an Error on home assistant side.
![image](https://user-images.githubusercontent.com/3395163/232179874-56692d78-0c40-433b-8697-c0d6f6f60dfa.png)

I can try to investigate on my own and give a log or something that might help. If you have any nudges or tips on where to look or what to enable to view the actual debug log, let me know!

`
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/simple_wyze_vac/vacuum.py", line 388, in async_set_fan_speed
    await self.hass.async_add_executor_job(lambda: self._client.vacuums.set_suction_level(device_mac=self._vac_mac, device_model=self._model, suction_level=wyze_suction))
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/simple_wyze_vac/vacuum.py", line 388, in <lambda>
    await self.hass.async_add_executor_job(lambda: self._client.vacuums.set_suction_level(device_mac=self._vac_mac, device_model=self._model, suction_level=wyze_suction))
  File "/usr/local/lib/python3.10/site-packages/wyze_sdk/api/devices/vacuums.py", line 263, in set_suction_level
    self._create_user_vacuum_event(event_id='WRV_SETTINGS_SUCTION', event_type=1)
  File "/usr/local/lib/python3.10/site-packages/wyze_sdk/api/devices/vacuums.py", line 302, in _create_user_vacuum_event
    return super()._create_user_event(VenusServiceClient.WYZE_APP_ID, event_id, event_type)
  File "/usr/local/lib/python3.10/site-packages/wyze_sdk/api/base.py", line 79, in _create_user_event
    self._general_api_client().post_user_event(pid=pid, event_id=event_id, event_type=event_type)
  File "/usr/local/lib/python3.10/site-packages/wyze_sdk/service/general_api_service.py", line 84, in post_user_event
    return self.api_call('/v1/user/event', json=kwargs)
  File "/usr/local/lib/python3.10/site-packages/wyze_sdk/service/general_api_service.py", line 62, in api_call
    return super().api_call(
  File "/usr/local/lib/python3.10/site-packages/wyze_sdk/service/base.py", line 204, in api_call
    return self.do_post(url=api_url, headers=headers, payload=json, params=params)
  File "/usr/local/lib/python3.10/site-packages/wyze_sdk/service/base.py", line 132, in do_post
    return self._do_request(client, req)
  File "/usr/local/lib/python3.10/site-packages/wyze_sdk/service/base.py", line 109, in _do_request
    raise e
  File "/usr/local/lib/python3.10/site-packages/wyze_sdk/service/base.py", line 91, in _do_request
    response = session.send(request, **settings)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
`

**Comment by romedtino** [comment]
The `error` states returned should be addressed in this release - https://github.com/romedtino/simple-wyze-vac/releases/tag/1.8.3

 (you can try it if you enable show beta releases on HACS -> Simple Wyze Vac)

Issue was Wyze added new names for states and they were not accounted for.
