### ISSUE TITLE
[BUG] requirement not found 

### ISSUE THREAD

**Issue by Scags104** [romedtino/simple-wyze-vac#59]
**Logs**
Logger: homeassistant.setup
Source: setup.py:206
First occurred: April 28, 2023 at 8:51:41 PM (1 occurrences)
Last logged: April 28, 2023 at 8:51:41 PM

Setup failed for custom integration simple_wyze_vac: Requirements for simple_wyze_vac not found: ['https://github.com/romedtino/wyze-sdk/archive/refs/tags/10.3.0.zip#wyze-sdk==10.3.0'].

**Simple Wyze Vac Version**
Latest
-

**Wyze Vacuum Firmware Version**
Latest beta
-

**Home Assistant Version**
2023.05.0b2 (since beta0)
-

**Additional context**
N/A

**Comment by Scags104** [comment]
@romedtino can you please advise

Thanks

**Comment by romedtino** [comment]
It seems like Home Assistant didn't install the dependencies for Simple Wyze Vac. Have you tried

- Uninstall Simple Wyze Vac through HACS
- Restart Home Assistant
- Reinstall Simple Wyze Vac through HACS
- Restart Home Assistant

If you still get the same error, connect to your Home Assistant installation and do a `pip list` does it show wyze-sdk? If it does, is it version 10.3.0? If it doesn't show, is there some nuance in your home assistant installation that prevents you from installing the python dependencies?

I'm also not familiar with what's in Home Assistant Beta 5, might be something new that prevents the dependency from installing correctly?

**Comment by Scags104** [comment]
@romedtino 

Seems i cant uninstall the integration since wyze-sdk is no longer installed, confirmed with pip list.

Dependency issue with wyze-sdk with new 2023.5.0bx poissibly?

**Comment by motoridersd** [comment]
I installed 2023.5.0b6 today and the error started happening after booting into it. Just installed b7 and issue is still there. 2023.5 definitely broke something.

**Comment by brianhanifin** [comment]
I also have this error. I am running Home Assistant OS 10.1 with Home Assistant 2023.05.0b7.

I was unable to remove the devices before I removed the integration. However, I was able to remove, restart, then reinstall the integration.

When I checked `pip list` (via the [Advanced SSH & Web Terminal](https://github.com/hassio-addons/addon-ssh) addon, wyze-sdk was missing. I was able to manually `pip install wyze-sdk` and version 1.10.0 is now installed.

After restarting a second time... oh shoot. Home Assistant won't startup and I'm having trouble gaining command line access.

**Comment by motoridersd** [comment]
Oh yeah. Forgot to mention I ran into the same problem when installing wyze-sdk via pip

I had console access and saw core was crashing with some php errors.

I restored a backup of my VM in Proxmox and was back up and running on 2023.4.6

**Comment by brianhanifin** [comment]
Well shoot. I've attempted to restore my automated backup from this morning from the Home Assistant command line. It claims it finishes successfully, but nothing changes. :(

**Comment by brianhanifin** [comment]
Oh, good. I was able to restore a backup from early this morning, then after I restarted we are backup! Thank you for the suggestion @motoridersd!

This is surprising behavior. I believe I have installed using pip at the OS command line in the past and not had any problems. Oh well.

**Comment by brianhanifin** [comment]
I tried reinstalling Simple Wyze Vac using HACS and the wyze-sdk is still missing in the `pip list`.

```
  OS Version:               Home Assistant OS 10.1
  Home Assistant Core:      2023.5.0

  Home Assistant URL:       http://homeassistant.local:8123
  Observer URL:             http://homeassistant.local:4357
➜  ~ pip list
Package    Version
---------- -------
awake      1.0
packaging  21.3
pathspec   0.11.1
pip        22.3.1
pulsemixer 1.5.1
pyparsing  3.0.9
PyYAML     6.0
retrying   1.3.3
setuptools 65.6.0
six        1.16.0
yamllint   1.31.0
```

**Comment by kennethpangky** [comment]
Just some info, I removed the the HACs integration, rebooted and installed it again. Didn't throw any errors, but when I tried to add it back via Devices & Services I got this error.

"Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

**Comment by romedtino** [comment]
Please standby. I think I've figured out the issue. It's related to more protobuf woes. 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
androidtvremote2 0.0.7 requires protobuf>=4.21, but you have protobuf 3.20.3 which is incompatible.
grpcio-reflection 1.51.1 requires protobuf>=4.21.6, but you have protobuf 3.20.3 which is incompatible.
grpcio-status 1.51.1 requires protobuf>=4.21.6, but you have protobuf 3.20.3 which is incompatible.
```

No need to comment that you're also having the issue. I'll update this issue when I have a resolution.

**Comment by romedtino** [comment]
Thanks for the patience. 

Please refresh HACS and try out beta 1.8.4 - https://github.com/romedtino/simple-wyze-vac/releases/tag/1.8.4

I think this resolves it but just in case, for now I'll leave it in beta.

Thanks.

**Comment by Scags104** [comment]
> Thanks for the patience.
> 
> Please refresh HACS and try out beta 1.8.4 - https://github.com/romedtino/simple-wyze-vac/releases/tag/1.8.4
> 
> I think this resolves it but just in case, for now I'll leave it in beta.
> 
> Thanks.

that did the trick thank you!
