### ISSUE TITLE
Will this change to Wyze login affect the intigration

### ISSUE THREAD

**Issue by Airey001** [romedtino/simple-wyze-vac#62]
Dear friend of Wyze,

As Wyze continues efforts to improve your experience and security, we are upgrading our authentication endpoint. We are reaching out to inform you of a few changes coming to the Wyze app that you know and love. 

As of July 7th, 2023 you will need to have updated your Wyze app beyond version 2.38 (Android and iOS devices) to be able to keep utilizing features as normal. Bottom line…now is the time to update your Wyze app.

As of now, you have 30 days before this change goes into effect. From that point, any app that is installed and is less than 2.38 will not be available for use. Please note that the latest Wyze app will need a minimum OS version to operate. 

Android: 7.0+

iOS: 14.0+

*For users of Home Bridge/Home Assistant   We have developed a portal for you to generate an API Key. Please follow [these steps](https://ablink.hello.wyze.com/ss/c/-06FoYlBl_ikXV2b_02xOOMHcihQGiSwNqQ1JZFffacvE4GbpOKAiklZTjOmxh0ifViW9XKcBcpF-ijZ_lY6sOHAi6OIORe9PQXGKJ9sYNf0Jfudd00j-v0e961-C4vf/3wu/DqwcamIHTYSZtPsTP4CIPA/h15/B3LoXwewjRb-fz4-HT8VpaPiw3UpF3C78vCHYRdaPlI) to update your script. Please make sure to update your script with this new endpoint to continue connecting to Wyze Cloud.

As always, your support means the world to us! We are here for you if anything comes up. Please contact [Customer Support](https://ablink.hello.wyze.com/ss/c/-06FoYlBl_ikXV2b_02xOOMHcihQGiSwNqQ1JZFffad21X5QTGKHKtfHSnXVEJGgd-OiGdWkyEt_6t2GG3ZXnQ/3wu/DqwcamIHTYSZtPsTP4CIPA/h16/aoaAcoLUasYaeSp3dMfYc493K7Il3wufL1FDJuSAQJY) if you run into any issues.

Many thanks,

Your friends at Wyze

**Comment by romedtino** [comment]
It might. This integration uses `wyze-sdk` under the hood so depending on that project's change, it might affect this integration. It might be that anyone who wants to use the integration will need to apply for the API key and that will be what is used to do logins

**Comment by romedtino** [comment]
Seems like things are still working good
