### ISSUE TITLE
[BUG] Control switches reset after rebooting HA

### ISSUE THREAD

**Issue by tdavis75** [romedtino/simple-wyze-vac#65]
I have some of my rooms unchecked.  When I reboot HA, and I go back into the Control section, I noticed that all of my rooms are switched back to on.  

I noticed this when I was upgrading HA from 2023.6.2 to 2023.6.3.  I'm running simple-wyze-vac version 1.8.4

**Comment by romedtino** [comment]
The room "switches" don't keep state. If you're interested in always running the vacuum with only specific rooms, then please see - https://github.com/romedtino/simple-wyze-vac/issues/40

**Comment by tdavis75** [comment]
Thank you! I ended up modifying my automation and defined the rules as you linked above.  It's working well after doing that.  Thank you!
