### ISSUE TITLE
Can't log in, appears to be due to the new API requirements

### ISSUE THREAD

**Issue by kennethpangky** [romedtino/simple-wyze-vac#66]
Hi, just observed can't log in today. From reading wyze-sdk it appears to be due to the new api.

https://github.com/shauntarves/wyze-sdk/pull/140

Just a post here for people who encounter the same issue. Looking forward to see it resolved/merged in due time thanks!

**Comment by romedtino** [comment]
Yeah, I'm watching the PR, just waiting for shaun to incorporate or see if he changes the approach. If it sits there for awhile, I'll probably just go ahead and pull on my fork. It seems the API will be the only way to really login now so I'll have to prompt for it at configuration setup regardless. Might as well bite the bullet now

**Comment by Mr-HaleYa** [comment]
Since you say you'll prompt on config, does that mean we all have to remove the integration and re-set it up to get that initial config popup or will it be in the same config menu as the polling settings?

Have you seen the [Docker Wyze Bridge](https://github.com/mrlt8/docker-wyze-bridge) and how it has multiple different ways to auth?
![image](https://github.com/romedtino/simple-wyze-vac/assets/42821995/8f25ea3a-5386-446f-8a48-ef9bba584b18)

**Comment by romedtino** [comment]
Yes, most likely going to have to remove integration and re-add due to this change since the login is really just the top level config flow and not the options flow. 

Docker Wyze Bridge looks like it uses its own authentication handler while I'm just piggy backing off of `wyze-sdk`. So I only have auth methods that `wyze-sdk` has

**Comment by romedtino** [comment]
Beta can be had here and auth seems to work with the upcoming PR of `wyze-sdk` - If you'd like to try it yourself:
https://github.com/romedtino/simple-wyze-vac/releases/tag/1.8.6

Don't forget:

- Update Simple Wyze Vac on HACS
- Before restarting Home Assistant, remove `Simple Wyze Vac` integration in `Settings -> Devices & Services -> Simple Wyze Vac -> Delete`
- Restart Home Assistant
- Add back integration in `Settings -> Devices & Services -> Add Integration`
- Choose ` Simple Wyze Vac`
- Provide username, password, key_id, api_key and totp

**Comment by kennethpangky** [comment]
Tested, works great. Thanks!

**Comment by PyroghostX** [comment]
Worked! Thanks for the quick fix

**Comment by PyroghostX** [comment]
only small thing is there is no headers for the key_id and api_key on the login popup, might confuse someone :P

**Comment by romedtino** [comment]
Awesome thanks! The last version should have those descriptions now and a blurb in the README mentioning it's a requirement to have the API key to use this integration. Thanks for trying it out!

**Comment by dinki** [comment]
@romedtino Thanks for providing this.  Try as I might, I cannot authenticate.  I updated HACS tried removing integration but I could not get it to work without restarting.  Restarted and removed.  Restarted again and then tried adding integration but it is failing.

I've generated the keys and the totp code from the setup auth page but it continues to tell me wrong username/password.   I know that I am using correct username and password as it is saved in vaultwarden.  Any ideas on what I might need to do?

**Comment by romedtino** [comment]
Before the mandatory KEY ID/ API KEY, were you able to login on simple wyze vac before using your username/password/totp?

**Comment by dinki** [comment]
> Before the mandatory KEY ID/ API KEY, were you able to login on simple wyze vac before using your username/password/totp?

Yes.  I have been using this integration for a very long time prior to needing the update.

**Comment by romedtino** [comment]
> > Before the mandatory KEY ID/ API KEY, were you able to login on simple wyze vac before using your username/password/totp?
> 
> Yes. I have been using this integration for a very long time prior to needing the update.
> 
> Can I just remove again, delete integration from disk (or make sure it's not there), restart, and reinstall and try again? I'd prefer not to have to set up the device/zones/etc if possible.

I think that should be fine. You shouldn't lose anything especially if the entity IDs just match the same ones once you add the integration back. If you can share the logs too if it has any errors related to the integration, that would be great.

**Comment by dinki** [comment]
> > > Before the mandatory KEY ID/ API KEY, were you able to login on simple wyze vac before using your username/password/totp?
> > 
> > 
> > Yes. I have been using this integration for a very long time prior to needing the update.
> > Can I just remove again, delete integration from disk (or make sure it's not there), restart, and reinstall and try again? I'd prefer not to have to set up the device/zones/etc if possible.
> 
> I think that should be fine. You shouldn't lose anything especially if the entity IDs just match the same ones once you add the integration back. If you can share the logs too if it has any errors related to the integration, that would be great.

Apologies for all of this.  I got it working.  Despite being able to log in without issue I decided to change my password.  I noticed that the minimum length of password is longer than the one I had been using.  I entered a new password and everything works now.  Ermmmff..   Working now so moving on.  Great work on getting this vac integrated.

**Comment by romedtino** [comment]
Closed as this is now fixed
