### ISSUE TITLE
[BUG] Cannot install, config flow fails

### ISSUE THREAD

**Issue by Lukejb14** [romedtino/simple-wyze-vac#68]
**Describe the bug**
Cannot install integration with the UI, it keeps failing. 

**To Reproduce**

After deleting integration, updating integration that uses Wyze sdk for api keys, restarting, and attempting to add integration via UI, see error. it fails and says “unknown error”. 

**Expected behavior**
Show configure flow to enter in account username, password and API account info.

**Screenshots**
![IMG_8662](https://github.com/romedtino/simple-wyze-vac/assets/11860191/db200175-d78f-4021-9add-d46f99f86568)
![IMG_8663](https://github.com/romedtino/simple-wyze-vac/assets/11860191/962a33a8-7e96-48f3-a9b4-cf5213d8a407)

**Simple Wyze Vac Version**
- 1.8.8

**Home Assistant Version**
- Home Assistant 2023.7.3
- Supervisor 2023.07.1
- Operating System 10.3
- Frontend 20230705.1 - latest

**Comment by romedtino** [comment]
Can you share the errors shown in the logs as well?

**Comment by tdavis75** [comment]
I had the same issue myself when I tried to follow the instructions to update it.  I rebooted my Pi that HA was running on a second time rather than just restart HA.  I was able to install the Simple Wyze Vac again.
