### ISSUE TITLE
HA 2024.5.0 deprecation warning

### ISSUE THREAD

**Issue by Intecpsp** [romedtino/simple-wyze-vac#79]
`Detected that custom integration 'simple_wyze_vac' calls async_create_task from a thread at custom_components/simple_wyze_vac/vacuum.py, line 77: vac.async_schedule_update_ha_state(force_refresh=True), please report it to the author of the 'simple_wyze_vac' custom integration`

**Comment by patwilliams87** [comment]
I'm seeing this in the logs in 2024.5.0 on my HA as well. The symptom of the deprecation is that the WYZE vacuum entities states appear to never update whether or not polling is on.

**Comment by MhatreRahul** [comment]
Can confirm, I do see the same error and the device does not seem to update irrespective of polling frequency.
