### ISSUE TITLE
Simple Wyze Vac will not reload

### ISSUE THREAD

**Issue by dwdonnelly** [romedtino/simple-wyze-vac#89]
**Describe the bug*
Vacuums stopped working.  Investigated Simple Wyze Vac integration within Home Assistant.  Found Simple Wyze Vac "Failed to set up".

**To Reproduce**
Non e- it is constant error.

**Expected behavior**
Expect to be able to reload, and reinitialize the integration to work.

**Screenshots**
![image](https://github.com/user-attachments/assets/f28a51cc-9c0b-4a76-8b19-3c21cecff643)

**Simple Wyze Vac Version**
1.9.1

**Wyze Vacuum Firmware Version**
1.6.313 and 1.6.213

**Home Assistant Version**
-2024.12.2

**Additional context**
I attempted to "configure" the integration, but the response was "Integration is already configured".

Itenpted to reinstall integration, response was "integration is already configured"

Restarted HA.  no impact, the problem remains.

Rebooted HA, no impact, the problem remains.

Log entries:

> Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 7:46:06 PM (4 occurrences)
Last logged: 7:58:36 PM

> Error setting up entry Simple Wyze Vac for simple_wyze_vac
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/simple_wyze_vac/__init__.py", line 95, in async_setup_entry
>     "filter": vac_info.supplies.filter.remaining,
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.13/site-packages/wyze_sdk/models/devices/vacuums.py", line 970, in remaining
>     return self.type.max_hours - self.usage
>            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
> TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

**Comment by tanderson1992** [comment]
Based on previous issue reports, I'm guessing this is due to the updated firmware. I'm following because my new vacuums are both at 1.6.2.13, and the integration gives me the same error.

**Comment by tanderson1992** [comment]
NVM, mine was an authentication error. I reloaded the integration with a corrected key, and it works. FWIW the docs state to copy the BASE32 secret, but during Wyze setup there are two codes given: a 16-character key to be copied into the authenticator app and a 36-character key the app cautions us to copy and keep in a safe place. That second one sounded more like a secret key to me, so that's what I used first. On second install I used the shorter key after seeing it verified in another issue here, and the integration loaded.

**Comment by dwdonnelly** [comment]
@tanderson1992   Hmm.  You have me a bit confused so let me walk into this slowly.

I have being adding vacuums for a couple of years now.  2 are at V1.6.213.  A third one I added several months ago is at V1.6.313.  As I was adding the fourth one, at V1.6.313, I got this error listed above or below (see logs).

So in the integration reload aspect:  When adding an integration, you get basically two choices:  Wyze and Simple Wyze Vac. I can authenticate with both.  So - I am confident I an using the correct keys and length of keys.

If I go to the Devices, Add Device, I get the "Wyze credentials" screen and enter: Username, Password, Wyze API Key ID, Wyze API Auth Key and the Base32 Key...then hit submit, it tells me Simple Wyze Vac is already configured.

If I try to "install the Simple Wyze Vac" integration, I get the same Wyze Credentials screen, enter the same information and get the same response: Simple Wyze Vac is already configured.

Also, the Wyze Integration is working properly.

So -  I went back to the logs:

Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 11:10:42 AM (3 occurrences)
Last logged: 1:58:44 PM

Error setting up entry Simple Wyze Vac for simple_wyze_vac
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/simple_wyze_vac/__init__.py", line 95, in async_setup_entry
    "filter": vac_info.supplies.filter.remaining,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wyze_sdk/models/devices/vacuums.py", line 970, in remaining
    return self.type.max_hours - self.usage
           ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'


Have to be honest, the log is not clear for me.....something about a filter info ...?  Its waiting to sync....?  Yup, I am lost in the logs.  Not a heavy coder.

Before I jump too far left or right, do you think there is any value in deleting the 4th Wyze vac ( the I am trying to add) from the Wyze App and see if that has an impact on the Simple Wyze Vac integration?  Am I correct in that when you add a vacuum in the Wyze app, its integration into HA via the integration makes it more or less immediately visible in HA?

Also, and how are you supposed to add vacuums?  Yes - I know, I have added two others and for the life of me I can not recall how I did it.  (Very bad on me).

Thanks in advance for your help.

**Comment by portalend** [comment]
Mine was doing the same thing. I got a second Wyze vacuum and selected reload on the integration to pull in the second vacuum and I got those same errors above. Ever hour or so I would try hitting reload on the integration and eventually it just worked. I didn't change anything between the attempts.... it just randomly worked. Both of my vacuums are on the latest firmware version.

**Comment by tanderson1992** [comment]
> Hmm. You have me a bit confused so let me walk into this slowly.

Sorry for the confusion. I was trying to "me, too" your error, but it looks like my issue was different. My first attempt resulted in the same `TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'` you are receiving, but after realizing I had used the wrong key, I deleted and re-installed the integration with the correct key. After that the integration loaded fine. Since you already had a working integration and then received this error, I'm guessing you're experiencing something different, and my posts should just be ignored.

**Comment by dwdonnelly** [comment]
@portalend Thanks for the reply! I am guessing now that is how I added the other two I have. Time to make notes in my HA Log. 
 For the newbie (like me), there should be a single sentence in the documentation explaining how to add a device.

Strangely, I have been randomly hitting the reload button...hoping something would happen.  More out of - "I need to try something" aspect.  But now appears that is what I need to do.

That in and of itself would seem to be a critical error or bug in the system - and would be a high priority fix. 

I will keep hitting the reload and maybe get lucky.  Thanks !

**Comment by dwdonnelly** [comment]
@tanderson1992 Never ignore a post....there is help within it.  Your comment certainly made me verify what I was doing and that was helpful.  As it gave me reassurance the integration was installed correctly and working - at least to a point (now - if it would just add the vacuum!).  And made me confirm the verification data I had.  So - all good.

I appreciate the help!

**Comment by dwdonnelly** [comment]
@romedtino Would appreciate your review of the following two comments:

Documentation Update:  There should be a single sentence in the documentation explaining how to add a device.

Bug:  Hitting the integration reload button does not add a new device.

Your thoughts?

**Comment by dwdonnelly** [comment]
@romedtino In continuing to troubleshoot this issue, where the integration will not reload and thus add an additional vacuum, I deleted the new vacuum from the Wyze app.  I went to HA and reloaded the simple-wyze-vac integration.  

The integration reloaded without error.

I then added the vacuum back into the Wyze app.  Then went to HA and reloaded the simple-wyze-vac integration.  But the integration would not load—the same errors as originally reported.

I have been trying @portalend suggestion of trying every few hours to reload the integration.  No success.

I have also reverified authentication as discussed with @tanderson1992.  I can authenticate with no problem.  But still, the integration will not successfully reload and add the additional vacuum.

I would appreciate your help on this issue.  Thanks in advance.

**Comment by romedtino** [comment]
Please stop tagging me. I am not customer support. I created this integration *to learn*, for *fun*, on my spare time *outside* of a full time job. It's the holidays.

I have already mentioned before and at the very top of the README this integration was tested against 1.6.202. Anything higher .e.g, [1.6.306](https://github.com/romedtino/simple-wyze-vac/issues/81#issuecomment-2242105755) or 1.6.313, I can't guarantee support as Wyze may or may not have different API calls. All API calls in this integration use wyze-sdk. If wyze-sdk does not support it, *this integration* cannot support it.

**Comment by dwdonnelly** [comment]
@romedtino My apologies.  Thank you.  Happy Holidays.

**Comment by jwgardner** [comment]
For this issue, check expired API key, they last a year
